# Dockerfile.next

# STAGE 1: Build
FROM node:20 AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx nx build web-client --prod

# STAGE 2: Production
FROM node:20
WORKDIR /usr/src/app
# Corrected path for your project structure
COPY --from=builder /usr/src/app/dist/web-client ./
COPY package*.json ./
RUN npm install --omit=dev
EXPOSE 4200
CMD ["node", "./server/main.js"]