# docker-compose.yml
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: procura_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  # Products Microservice
  products-service:
    build:
      context: .
      dockerfile: Dockerfile.nest
      args:
        APP_NAME: products-service
    container_name: products-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=procura_db
    depends_on:
      - postgres
    networks:
      - app_net

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.nest
      args:
        APP_NAME: api-gateway
    container_name: api-gateway
    ports:
      - '3000:3000' # Expose the gateway to the host
    depends_on:
      - products-service
      - orders-service
    networks:
      - app_net
    
  orders-service:
    build:
      context: .
      dockerfile: Dockerfile.nest
      args:
        APP_NAME: orders-service
    container_name: orders-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=procura_db
    depends_on:
      - postgres
      - products-service
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net: