# Dockerfile.nest

# STAGE 1: Build
FROM node:20 AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
ARG APP_NAME
RUN npx nx build ${APP_NAME} --prod

# STAGE 2: Production
FROM node:20
WORKDIR /usr/src/app
# Corrected path for your project structure
COPY --from=builder /usr/src/app/dist/${APP_NAME} ./
COPY package*.json ./
RUN npm install --omit=dev
CMD ["node", "main.js"]